# Generated by Django 6.1 on 2026-09-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='alilities',
            new_name='abilities',
        ),
    ]
